- hosts: aws
  become: yes
  tasks:
    - copy:
        src: Task-3-Deployment/index-aws.html
        dest: /var/www/html/index.html
        mode: '0644'

    - service:
        name: nginx
        state: restarted

- hosts: azure
  become: yes
  tasks:
    - copy:
        src: Task-3-Deployment/index-azure.html
        dest: /var/www/html/index.html
        mode: '0644'

    - service:
        name: nginx
        state: restarted
