- hosts: aws
  become: yes

  tasks:
    - name: Deploy AWS index page
      copy:
        src: index-aws.html
        dest: /var/www/html/index.html

- hosts: azure
  become: yes

  tasks:
    - name: Deploy Azure index page
      copy:
        src: index-azure.html
        dest: /var/www/html/index.html
