upstream backend {
    server 18.207.213.206:80 max_fails=3 fail_timeout=10s;
    server 20.97.24.45:80 backup;
}

server {
    listen 80;

    location / {
        proxy_pass http://backend;
    }
}
