pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/Aashishk25/Capstone-Project.git'
            }
        }

        stage('Debug') {
            steps {
                sh 'pwd && ls -R'
            }
        }

        stage('Configure') {
            steps {
                sh 'ansible-playbook -i Task-2-Configuration/inventory.ini Task-2-Configuration/nginx-playbook.yml'
            }
        }

        stage('Deploy AWS') {
            steps {
                sh 'ansible-playbook -i Task-2-Configuration/inventory.ini Task-3-Deployment/nginx-deploy.yml --limit aws'
            }
        }

        stage('Deploy Azure') {
            steps {
                sh 'ansible-playbook -i Task-2-Configuration/inventory.ini Task-3-Deployment/nginx-deploy.yml --limit azure'
            }
        }
    }

    post {
        success {
            echo "Deployment successful"
        }
        failure {
            echo "Deployment failed"
        }
    }
}
