[aws]
app ansible_host=<AWS_APP_IP> ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[azure]
vm ansible_host=<AZURE_IP> ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/id_rsa
