- hosts: all
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure nginx running
      service:
        name: nginx
        state: started
        enabled: yes
        
    - name: Check nginx status
      command: systemctl status nginx
      register: nginx_status

- debug:
    var: nginx_status.stdout
